version: "3.7"
services:
  component:
    image: docker.pkg.github.com/fishey2/java-component-template/component:0.1-SNAPSHOT
    build:
      context: .
      dockerfile: docker/component/Dockerfile
    ports:
      - 8080:8080
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: bitnami/kafka
    ports:
      - "9092"
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock